name: Build & Lint
run-name: ${{ github.actor }} is testing building the project 🚀
on:
  pull_request:
    branches:
      - main # Or your main branch name

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Set environment variables
        run: |
          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" >> $GITHUB_ENV
          echo "AUTH_GITHUB_ID=${{ secrets.AUTH_GITHUB_ID }}" >> $GITHUB_ENV
          echo "AUTH_GITHUB_SECRET=${{ secrets.AUTH_GITHUB_SECRET }}" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "TURSO_DATABASE_URL=${{ secrets.TURSO_DATABASE_URL }}" >> $GITHUB_ENV
          echo "TURSO_DATABASE_AUTH_TOKEN=${{ secrets.TURSO_DATABASE_AUTH_TOKEN }}" >> $GITHUB_ENV
          echo "NODE_ENV=production" >> $GITHUB_ENV
          echo "VAPID_PRIVATE_KEY=${{ secrets.VAPID_PRIVATE_KEY }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_POSTHOG_KEY=${{ vars.NEXT_PUBLIC_POSTHOG_KEY }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_POSTHOG_HOST=${{ vars.NEXT_PUBLIC_POSTHOG_HOST }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_VAPID_PUBLIC_KEY=${{ vars.NEXT_PUBLIC_VAPID_PUBLIC_KEY }}" >> $GITHUB_ENV
          echo "SKIP_ENV_VALIDATION=true" >> $GITHUB_ENV

      - name: Build Next.js app
        run: pnpm build
