name: Build & Lint
run-name: ${{ github.actor }} is testing building the project 🚀
on:
  pull_request:
    branches:
      - main # Or your main branch name

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js app
        run: pnpm build
        env:
          # Server-side environment variables
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
          AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}

          # Database configuration
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
          TURSO_DATABASE_AUTH_TOKEN: ${{ secrets.TURSO_DATABASE_AUTH_TOKEN }}

          # Other server variables
          NODE_ENV: 'production'
          VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY }}

          # Client-side environment variables
          NEXT_PUBLIC_POSTHOG_KEY: ${{ vars.NEXT_PUBLIC_POSTHOG_KEY }}
          NEXT_PUBLIC_POSTHOG_HOST: ${{ vars.NEXT_PUBLIC_POSTHOG_HOST }}
          NEXT_PUBLIC_VAPID_PUBLIC_KEY: ${{ vars.NEXT_PUBLIC_VAPID_PUBLIC_KEY }}

          # Optional: Skip validation during CI build if needed
          SKIP_ENV_VALIDATION: 'true'
